### ISSUE TITLE
GET_ALL_USERS should be made conditional on the front end to avoid unauthorized action error

### ISSUE THREAD

**Issue by jasminabasurita** [Choko-Hopper/choko-hopper#104]
AllUsers.js 15:20

Error: Request failed with status code 403
Stack trace:
createError@http://localhost:8080/bundle.js:4100:15
settle@http://localhost:8080/bundle.js:8927:12
handleLoad@http://localhost:8080/bundle.js:3939:7

**Comment by annabelnlau** [comment]
Is it not? I logged in as a regular user (dan@dan.com) and the All Users button was no longer visible

**Comment by annabelnlau** [comment]
Ah, I see. The page still renders but doesn't show the actual users. I'll take a look!

**Comment by jasminabasurita** [comment]
I'm still seeing the error, but I see where it's coming from! It looks like a small quick fix
